- StudioCore/Scene/SceneRenderPipeline.cs
For whatever reason we're sometimes getting out of bounds indices for selections. Root causing this will take some effort but in the meantime checking the bounds should help.
> Add bounds check for selections

- SoulsFormats/SoulsFormats/Formats/FLVER/FLVER2/FaceSet.cs
- StudioCore/Resource/FlverResource.cs
Both soulsformats flver and map studio flver didn't handle 16-bit indices well once it increases past a certain size. This should make sure 16-bit and 32-bit indices are handled right no matter the destination buffer size.
> fix poor handling of 16-bit indices

- SoulsFormats/SoulsFormats/Util/BinaryReaderEx.cs
This optimizes ReadUTF16, previously a huge source of temporary allocations that had to be GCed, to not need all the allocations and improves loading performance significantly.
> Don't create a byte[] array for every UTF16 codepoint

- SoulsFormats/SoulsFormats/Util/BinaryReaderEx.cs
- StudioCore/Resource/FlverResource.cs
In particular reading big endian values should now be allocation free.
> Some more changes to help reduce memory allocations while loading

- StudioCore/TextEditor/FMGBank.cs
Affects Sekiro. Fixes missing "Skill" FMG, and adds custom labels for "Loading title/text" FMGs.
> FMG: fix missing entry, add custom labels.

- StudioCore/ParamEditor/ParamRowEditor.cs
Fixes behaviour inside some context menus where selectable had been used inside submenus, causing erratic navigation behaviour
> Fix editor mode context menus

- StudioCore/Gui/Viewport.cs
- StudioCore/MsbEditor/SceneTree.cs
- StudioCore/MsbEditor/Selection.cs
Adds the following functionality:
Ctrl+Click toggles target selection while preserving existing non-target selection.
Shift+Click selects all objects between existing selection and targeted selection.
> MSB map object list multi-select improvements

- StudioCore/ParamEditor/SearchEngine.cs
Allows prop search to search dummy8 fields (maybe considered a fix as prior behaviour would match "System.Byte[]")
> Allow prop search to search dummy8

- StudioCore/MsbEditor/Entity.cs
- StudioCore/MsbEditor/Gizmos.cs
Offset gizmo by translation node
Hide gizmo when entire selection isn't translatable
Fix incorrect object rotation "center" due to translation node position (node w/ rotation is not fixed)
> Gizmo offset by translation node & improvements

- StudioCore/ParamEditor/ParamBank.cs
This is for where version number differs or is absent.
> Ignore parambnd version for non-ER games 

- StudioCore/ParamEditor/ParamRowEditor.cs
Fixes a crash when switching from one field to another. Also fixes a propcache is null error that I thought was already fixed.
> Discard propcache when parse fails

- StudioCore/MsbEditor/ModelEditorScreen.cs
For when model bounds can't be calculated, since even empty models still have points of interest like DummyPolys.
> Give Model Editor minimum camera speed

- StudioCore/MsbEditor/SceneTree.cs
This prevents several bugs from cropping up, including at least one that ends up crashing the program.
> Fix old type view caches being kept and used when a map is unloaded then re-loaded

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
This assert allows the user to render an MSB completely inaccessible to SF, as the assert is only checked on MSB read and not write. So an MSB can be saved successfully at first, but upon re-save or re-load (when MSB is read) the assert will render the MSB unusable from then on.
> Remove user-harmful assert

- StudioCore/Resource/ResourceLoadPipeline.cs
- StudioCore/Resource/ResourceManager.cs
I think something that happened with resource loading may have made DSMapStudio less stable. TPF resources that don't load are causing hard crashes. DirectoryNotFoundExceptions are also happening because of some of the debug maps referencing directories that just aren't on the disc. 
Specifically, `DemonsSoul\data\Model\obj\o0050\tex\o0050.tpf` fails when loading m99_99_97_00 and a good few of them reference a file in a folder that doesn't exist which ends up giving that exception instead of the FileNotFoundException you cover for.
> Resource loading fixes

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
Another assert that can lock MSB. This one also happened by default when creating a "new" enemy.
> MSBE: Remove assert & add default value for EnemyBase UnkT24

- StudioCore/MsbEditor/Gizmos.cs
Fixes Gizmo rotation not being affected when Space is set to World if selection contains more than 1 entity.
> Make gizmo rotation respect GizmoSpace.World with multiple selections

- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioCore/ParamEditor/SearchEngine.cs
Fixes dupe FMG entries crashing the program.
> Make Param Decorators handle dupe FMG entries instead of crashing

- StudioCore/MapStudioNew.cs
- StudioCore/TextEditor/FMGBank.cs
- StudioCore/TextEditor/TextEditorScreen.cs
Fix FMGs being loaded twice on program start when recent project is valid.
Fix WeaponEffect not being editable.
Detect duplicate FMG entries and ask user if duplicates should be removed.
Tick currently selected FMG language in select language UI.
Move Location and Characters out of Item UI section.
> FMG Editor Fixes & Improvements

- StudioCore/ParamEditor/ParamMeta.cs
prevents crash when it tries to write to the file
> Create parammeta file if not existing

- StudioCore/TextEditor/FMGEditor.cs
Fixes FMG text changes applying to wrong entry when another entry is selected while a text box is being edited (when program speed was fast enough)
> Fix FMG text changes applying to wrong entry

- StudioCore/CFG.cs
- StudioCore/MapStudioNew.cs
- StudioCore/MsbEditor/SceneTree.cs
Adds CFG options for loaded maps to ignore search filter & loaded maps to be pinned to top of map list
(both are currently on by default)
> Add CFG options related to loaded maps in map list

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
Point.bt has a comment that these are part indices. They have been indices in randomizer for a while now.
This may be tricky to fix if any of them have gotten offset in people's maps. I made a basic dump of vanilla ones, but something automated may be needed: <https://gist.github.com/gracenotes/592b59b35fc98180eb29022619079ac4>
But let's fix this now before future issues arise.
> Add part references in GroupDefeatReward

- StudioCore/MsbEditor/PropertyEditor.cs
Fixes MSB properties not actively updating before changes are committed, such as with click-dragging floats. 
Issue was introduced in #165 multi-selection editing
> Reimplement MSB currently changing prop exec/undo

- StudioCore/ParamEditor/MassParamEdit.cs
- StudioCore/ParamEditor/ParamBank.cs
Import newly used fields (including "expanded" byte arrays) from vanilla param while upgrading params.
Also fixes MassEdit VanillaRef .
> More 1.07 param upgrade tasks

- StudioCore/MsbEditor/PropertyEditor.cs
Fixes MSB properties that are being indirectly modified before changes are committed, such as with click-drag float elements.
Issue was introduced in https://github.com/soulsmods/DSMapStudio/pull/165 multi-selection editing
(Figured out what went wrong the first time, turned out to be simpler than I thought)
> Fix MSB click-drag properties

- StudioCore/ParamEditor/ParamEditorScreen.cs
Prevents users from upgrading params into a new versions before we properly support it (preventing them from prematurely screwing up their params).
When new param versions are released, we would include its version number in ParamUpgradeER_TargetWhitelist.
Thoughts on this would be appreciated.
> Add version whitelist for allowing param upgrading

- StudioCore/ParamEditor/ParamEditorScreen.cs
Replace whitelist list, and just use whitelist threshold instead. Increase threshold # to encompass all 1.07.x regulations.
v1 was a bit of a premature PR, was hoping to get more feedback first. This whitelist concept is a bit looser, and I don't think defs have ever changed between matching 1.XX versions.
> Param upgrade whitelist v2

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
- StudioCore/MsbEditor/Universe.cs
This change is somewhat inconvenient, because it mismatches other games, but it is the correct thing to do. I've checked all instances of these values in all Elden Ring MSBs and they are always positive and the default values of all of these fields is 0. In all formats for which we have official defs, as well as in decompiled code, these values have all switched to uints. It is what fromsoft has decided, and will probably carry into future RPG titles.
This should be fine for the purpose of migrating existing data files, since there is no data loss. If someone incorrectly entered -1 as the default value of any of these fields, the game is already interpreting it as 4294967295 anyway.
> Change EntityID and EventFlagID fields to uint in MSBE

- FSParam/Param.cs
Fixes conflict with single entry params in old format that writes the param type in the param header.
> Don't add string.empty at the start of param.

- StudioCore/MsbEditor/SceneTree.cs
Hotfix for keyboard navigation acting poorly with identically-named selectables (previously, it highlighted multiples at once and messed up future keyboard nav). This may have been fixed in newer versions of ImGui?
Also makes a minor improvement to keyboard nav when there is a mass selection. In short, pressing [JUST] up/down arrow will make next selection exclusive instead of maintaining current multi-selection.
> MSB Scenetree keyboard fixe

- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioCore/ParamEditor/SearchEngine.cs
- StudioCore/TextEditor/FMGBank.cs
- StudioCore/TextEditor/TextEditorScreen.cs
Sets up stuff that will allow handling text better in future updates (especially by outside systems).
Fixes FMGs with multiple patch FMGs not always loading (and overriding) in the correct order.
Fixes a potential issue when trying to find the parent FMG for "TitleGoods_DLC1" due to per-game differences being checked before all FMGs were loaded.
Also cleans up a bit, and adds some additional per-game difference handling in ApplyGameDifferences(); (ReusedFMG_32).
> TextEditor misc. improvements

- StudioCore/MsbEditor/MsbEditorScreen.cs
Makes (non-undo/redo) hotkeys no longer require clicking the viewport if another UI element was previously selected.
Also forbids undo/redo the same as other hotkeys, preventing them from being enabled when ImGui input elements are active which conflicted with generic input undo/redo.  Should also prevent issues stemming from non-default keybinds for undo/redo.
> Improve map editor hotkey permission

- StudioCore/AssetLocator.cs
Typing "AEG" in a model name field was enough to trip it.
> Fix crash when model name fields referenced AEG, but weren't long enough to derive AEG folder path

- StudioCore/ParamEditor/ParamReloader.cs
Fixes exceptions thrown during hot reloading (silently) crashing the program instead of being ignored or caught by the crash handler.
Seems to slightly impact performance. Function took ~15% longer when reloading multiple params.
> Use tasks instead of threads for param hot reload

- SoulsFormats/SoulsFormats/Formats/BTL.cs
These fields are responsible for confusing EVERYBODY who tries to edit BTL lights in ER (myself included).
Unfortunately, we lack some big details on what they do - but enough is known, and they are important enough that I think a temp name like this is warranted.
> Add temp name for BTL UnkC0

- StudioCore/MapStudioNew.cs
Remove original (now duplicate) "Open Config Folder" option from settings menu. Move "Open in Explorer" down one slot and uncapitalize the I.
> Nitpicky minor "Open in Explorer" tweaks & add Nordgaren to in-program contributor credits

- StudioCore/Assets/GameOffsets/DS1/CoreOffsets.txt
- StudioCore/ParamEditor/ParamReloader.cs
Checks exe dos header for offset of new header, as the dosstub is bigger in the debug exe. Will eventually switch out for AoBs
> Fix for Debug EXE

- StudioCore/CFG.cs
- StudioCore/Editor/UIHints.cs
- StudioCore/ImGuiRenderer.cs
- StudioCore/MapStudioNew.cs
- StudioCore/MsbEditor/DisplayGroupsEditor.cs
- StudioCore/MsbEditor/ModelEditorScreen.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
- StudioCore/MsbEditor/PropertyEditor.cs
- StudioCore/MsbEditor/SceneTree.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioCore/ParamEditor/ParamRowEditor.cs
- StudioCore/Resource/ResourceManager.cs
- StudioCore/Scene/CreatePrefabModal.cs
- StudioCore/TextEditor/TextEditorScreen.cs
Renamed font scale to UI scale and added it as a multiplier to various sizes in the program. This is to make the program appear uniform at different monitor sizes where one might choose to scale it up.
Also, changed the UI scale slider to only perform scaling when let go of, and lowered its rounding to steps of 0.05.
Note that this is not a comprehensive solution. Dear ImGui says the following about DPI awareness:
> ### Q: How should I handle DPI in my application?
> 
> The short answer is: obtain the desired DPI scale, load your fonts resized with that scale (always round down fonts size to the nearest integer), and scale your Style structure accordingly using `style.ScaleAllSizes()`.
> 
> Your application may want to detect DPI change and reload the fonts and reset style between frames. …
> Transform Font scale to UI scale.

- StudioCore/MsbEditor/Action.cs
- StudioCore/MsbEditor/Entity.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
- StudioCore/MsbEditor/ObjectContainer.cs
- StudioCore/MsbEditor/SceneTree.cs
Adds create BTL Light option in create menu.
Makes BTL implementation a bit cleaner and (moderately) less stupid.
BTL lights now utilize entity parent/child system for organizing which lights belong to which BTL.
Adjusts CloneMapObjectsAction and AddMapObjectsAction to work better with parent/children (this shouldn't affect any pre-existing behavior).
Cleans up old/commented-out code.
Fixes a very minor bug with BTL Hide All/Unhide All UI element visually reflecting first light's hidden state.
> BTL improvements & cleanup. Add Create BTL Light option

- StudioCore/MsbEditor/AssetBrowser.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
* "Goto ID" no longer goes to a pinned ID, but the actual ID in the list.
* "Goto ID" no longer goes to 0 if you did not enter anything and just click out of the popup.
* Search bar in Model Editor Asset Browser no longer scrolls along with the list.
> Small tweaks to editors.

- StudioCore/InputTracker.cs
Prevents unrecognized keys from trigging unbound key binds.
> Don't add unknown keys to _newKeysThisFrame

- StudioCore/MsbEditor/Action.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
Fix crash when trying to target dupe a root object.
Fix target dupe not changing entity's parent.
Fix BTL light target dupes not working, added functionality to target a BTL.
> MSB targeted dupe fixes

- StudioCore/AssetLocator.cs
- StudioCore/CFG.cs
- StudioCore/Editor/ProjectSettings.cs
- StudioCore/MapStudioNew.cs
- StudioCore/TextEditor/FMGBank.cs
- StudioCore/TextEditor/FMGEditor.cs
- StudioCore/TextEditor/TextEditorScreen.cs
Adds option in settings menu to separate grouped FMGs in the editor (I.E. title, description, summary).
Adds option in settings menu to separate patch FMGs (I.E. DLC).
Adds "Previously used FMG language" to project settings file, which is used to remember which FMG language to load on project load.
FMG reload is a task (once again).
Misc cleanup, improvements, and minor fixes.
> Add FMG editor separate options (+ improvements)

- StudioCore/ParamEditor/ParamUtils.cs
From MassEdit branch, but that's not being pulled and apparently this fix was there instead of somewhere reasonable
> Fix crash on some comparisons

- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
Allows editing DrawParams in the param editor.
Currently, you toggle between viewing GameParam and DrawParam via UI checkbox. This isn't _super_ great, but it's enough for base functionality.
Incidentally fixes a crash when VanillaBank is missing a key, which also prevents crashing in other situations (notably, when a paramdef cannot be applied to VanillaBank due to paramdef updates.
> DrawParam editing

- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioUtils/StridedByteArray.cs
Fix expansion on capacity 1 strided arrays
Confirm selection exists when pasting after selection.
Properly clean selection state when deleting rows.
>  Fix Sort Rows on 1 row params, Fix Paste after selection with no selection

- StudioCore/MsbEditor/Universe.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
Base solution to just get everything exposed and open to useful param editor features. Uses same filter system as DrawParams.
* Exposes the previously-culled DS2 map params to param editor in toggleable filter (note: some were not culled and were double exposed in MSB and param anyway).
* Try/Catch DS2 ApplyParamDef, like other games do.
* Map Editor now uses ParamBank's params, so changes are now immediately shared between the two editors. DS2 maps now require a loaded ParamBank.
> DS2 map params in param editor

- StudioCore/CFG.cs
- StudioCore/KeyBindings.cs
- StudioCore/MapStudioNew.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
Adds an action to rotate an object around the X and Y axis by a fixed amount with the press of a keybind (J for X axis, K for Y axis). The fixed amount for both can be changed in the Map Settings menu.
Adds an action to reset the current rotation of an object to 0, 0, 0 with the press of a keybind (L).
> Add Arbitrary Rotation X/Y action, Reset Rotation action

- StudioCore/CFG.cs
- StudioCore/MapStudioNew.cs
- StudioCore/MsbEditor/Gizmos.cs
- Added gizmo color settings, allowing the user to configure the colors used by the gizmo tool for the X, Y and Z axis.
- Added a button in the Gizmo section that resets the gizmo colors to the 'default' colors.
> Add the ability to change Gizmo color

- DSMapStudio/DSMapStudio.csproj
- DSMapStudio/Program.cs
- StudioCore/MapStudioNew.cs
Make Crash Handler handle UnhandledException properly.
Use Assembly version for program version.
Clear recent project in CFG if an exception occurred while trying to load project.
Handle missing oodle dll in game folder.
> Crash handling fixes and improvements

- StudioCore/InputTracker.cs
Example: pressing keys Shift+Ctrl+Z would cause Z, Ctrl+Z, Shift+Z, and Ctrl+Shift+Z to pass.
> Fix input tracker not properly checking conditional keys

- StudioCore/TextEditor/FMGEditor.cs
Fix crash when deactivating FMG text editor when no changes have been made for anything at any point in the past
> Fixed FMG editor crash

- StudioCore/Assets/Paramdex/DS2S/Defs/ITEM_LOT_PARAM2.xml
- StudioCore/ParamEditor/ParamUtils.cs
This crash only became relevant because DS2 loose params were able to load in without proper paramdef checks - should look into this more later.
Fixing it because a similar issue might crop up later anyway.
> Fix ds2 def, prevent crash when diffing with undef'd vanilla

- StudioCore/AssetLocator.cs
- StudioCore/MapStudioNew.cs
Makes EBOOT.BIN files visible by default.
> Make game executable browser file name filter include EBOOT.BIN

- StudioCore/Editor/CacheBank.cs
- StudioCore/ParamEditor/ParamRowEditor.cs
Also fixes calccorrectgraph graph, which was using a shared context object (the row)
> Add key distinction to cachebank

- StudioCore/CFG.cs
- StudioCore/MapStudioNew.cs
Fix recent projects selectables with identical names.
Add right-click context option to remove project from recent projects list.
Increases the recent project limit from 10 to 20.
> Recent project list improvements

- StudioCore/MsbEditor/Entity.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
**Please review in detail, I'm not sure about the consequences of my AddChild change**
Poked around in the debugger until I found a place which stored the currently relevant map and its relevant transform offset, then applied that to the selection blindly. Sure hope that makes sense!
The Container change is secondary and doesn't really seem to be relevant, but it seems like good practice. Duplicated map entities did not have their Container (ContainingMap) changed correctly.
> Fix offset on Move Selection to Camera

- StudioCore/ParamEditor/ParamBank.cs
Makes DeS params write to every potential parambnd variation, because DSMS doesn't know which one a mod may provide and which one the game may use (which can be any of the 4). Also uses a prioritized list of parambnds when trying to load.
This prevents [new] users from making a param modification and having it not work because the wrong parambnd was written to.
> Write DeS params to every parambnd variations

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
Introduced in #346, was never in a release.
Caused by SF reading an int enum.
I don't know why SF enum read insists on uint (seems like an oversight?), but it doesn't matter for this enum anyway so that'll be a task for another day.
_(I'm not sure why it didn't cause an issue during initial testing. I remember testing the enums, but I guess I couldn't have! Oops!)_
> Fix crash when loading HorseRideOverride

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
Fixes issue introduced in #404 (was never in an official release).
Map reference detection specifically wants a byte array instead of a sbyte array. (BuildReferenceMap() in Entity.cs).
Having it as an sbyte array in the first place barely matters (wild card IDs are 255 instead of -1) and _all_ the other games use byte, so I'm just reverting my previous change to make everything consistent again.
> Fix ER map node references

- StudioCore/CFG.cs
- StudioCore/ParamEditor/ParamRowEditor.cs
- StudioCore/SettingsMenu.cs
Will now always show the "secondary" field name in the context menu on right click.
So if it's using the Alt Names, will show the internal name, and vice versa.
The brackets can now be toggled on/off.
Also changed the names of the field name settings in the menu a little.
> Clean field labels in param editor

- StudioCore/MsbEditor/SpecialMapConnections.cs
The positioning and offset of Elden Ring maps to one another assumes the existence of certain map IDs.
This breaks when you load the CNT, because it does not contain some of these maps.
This commit simply adds some IF cases to actually check for the existence of those maps, before setting their offsets. Now, CNT can be used in DSMS again.
> Load CNT maps (Sanity check some custom cases)

- StudioCore/ParamEditor/ParamBank.cs
The notadded search command was foolishly replaced with a not toggle for any command. The built-in upgrade commands weren't fixed wrt to this, except in the masseditvars branch.
This should be fixed before release, which may not contain masseditvars.
> Fix upgrade commands from vars branch

- StudioCore/Resource/FlverResource.cs
- StudioCore/Resource/NVMNavmeshResource.cs
Basically, if a mesh has bone indices, but no weights, said mesh should transform by the specified bone. This is very apparent since in such cases for DeS, all bone indices are the same bone too, but I don't think this needs to be tested.
Bone transforms are prefetched and cleared to avoid computing transforms every loop iteration on a vertex for these.
In addition, NVM Gates are colored a green color to indicate them as they're the most important tag a polygon can have. This change will show up for Dark Souls 1 as well.
> Des transform fix and DeS/DS1 NVM Gate coloring

- README.md
Fixes readme since we require 7.0 now.
Moves requirements closer to the top of the list, in the hopes that more people will see it.
> Fix readme for 7.0 .NET requirements. Move requirements upwards

- StudioCore/ParamEditor/SearchEngine.cs
Makes mergeable and conflicts searches more accurate when multiple auxparams involved and when searched from auxparam.
Prior behaviour is that for a primary bank row, it is classed mergeable when unmodified and there is any number of modifications in aux banks.
New behaviour is that for a primary bank row, it is classed mergeable when unmodified and there is only one modification in aux banks.
Prior behaviour is that for an aux bank row, is it classed mergeable when unmodified and there is any number of modifications in aux banks (including itself)
New behaviour is that for an aux bank row, it is classed mergeable when the primary bank is unmodified and there is only one modification in aux banks (presumed itself. While this may appear to cause issues for someone aiming to place these …
> Change to mergeable & conflicts searches

- StudioCore/ParamEditor/ParamUtils.cs
It would be nice to also fix sekiro's defs (networkparam) but I can't guarantee those aren't authentic.
> Disambiguate fields of duplicate names in propertyeditor

- StudioCore/MsbEditor/ObjectContainer.cs
- StudioCore/MsbEditor/SceneTree.cs
- StudioCore/MsbEditor/Universe.cs
Properly hooks up DS2 generator locations to MapOffsetNode, which also fixes locations being too offset on successive map loads.
Prevents user trying to load DS2 maps before params are fully loaded, fixing a potential crash.
> Ds2 map offset fix. & forbid DS2 map load before param load

- StudioCore/ParamEditor/ParamMeta.cs
At a minimum, fixes crash introduced in #448.
> Override param meta enum keys instead of crashing

- StudioCore/MapStudioNew.cs
Adds a tab to the new project menu that optionally allows user to provide a directory for game files instead of targeting an executable. Requires user to define game type manually.
Also makes it so when a new project's project folder already contains a project.json, it will prompt user to replace it instead of refusing to continue.
> Add "advanced" tab to new project menu for more user control

- StudioCore/MsbEditor/MsbEditorScreen.cs
When swapping between editors, multiple elements in one window will just display whatever runs last.
PR makes prop editor shown instead of prop search, and render group editor instead of resource list
> Change default UI tabs shown in map editor when swapping editors

- StudioCore/MapStudioNew.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
- StudioCore/MsbEditor/SceneTree.cs
- StudioCore/MsbEditor/SpecialMapConnections.cs
- StudioCore/MsbEditor/Universe.cs
Adds option to load all maps directly related to an overworld tile map.
Example: for _02 maps, it will load all overlaid _01 and _00 maps. _00 maps will load its related _01 and _02 maps.
Adds an option to unload all currently loaded maps (+ confirmation).
> Add options to load related overworld maps, unload all maps. & cleanup

- StudioCore/ParamEditor/ParamEditorScreen.cs
> Wait for meta to load before allowing param editing

- StudioCore/MsbEditor/PropertyEditor.cs
- StudioCore/ParamEditor/ParamRowEditor.cs
No option to toggle on/off (ATM).
Also contains a little setup for merging param/msb prop editor UI functions somewhere down the road.
> Display value type in MSB/Param property editors

- StudioCore/Scene/TexturePool.cs
- Veldrid/ResourceLayoutElementDescription.cs
- Veldrid/Vk/VkDescriptorPoolManager.cs
- Veldrid/Vk/VkGraphicsDevice.cs
- Veldrid/Vk/VkResourceLayout.cs
- Veldrid/Vk/VkResourceSet.cs
* Vulkan initialization will now explicitly check all available GPUs for the features it needs until it finds one with everything that's needed is supported while prioritizing dedicated GPUs.
* Attempt at fixing startup crash on Intel GPUs by making the bindless texture pools update after bind, which gives Intel GPUs a much higher sampled image limit.
> Rework initialization and maybe fix Intel GPUs

- StudioCore/MsbEditor/DisplayGroupsEditor.cs
Adds feature to right click render groups to highlight them in UI, along with button to clear highlights.
Makes render group UI more compact.
Shortens option names and makes get/give terminology more distinct.
Technically prevents a future issue if we ever need to support 11+ render groups (due to "##dispgroup{g}{i}").
> Add render group highlight feature + UI tweaks

- StudioCore/CFG.cs
- StudioCore/Editor/ProjectSettings.cs
- StudioCore/MapStudioNew.cs
Try/Catch deserialization. When it fails, inform user then delete project.json, preventing a crash on load loop (same system as config and keybinds).
If a targeted project.json file doesn't exist when trying to load it, inform user and remove it from CFG recent projects list/last instead of doing nothing.
> Improve project.json load error handling

- StudioCore/ImGuiRenderer.cs
- StudioCore/Resource/FlverResource.cs
- StudioCore/Resource/HavokCollisionResource.cs
- StudioCore/Resource/HavokNavmeshResource.cs
- StudioCore/Resource/NVMNavmeshResource.cs
- StudioCore/Scene/FullScreenQuad.cs
- StudioCore/Scene/GPUBufferAllocator.cs
- StudioCore/Scene/Renderer.cs
- Veldrid/CommandList.cs
- Veldrid/Util.cs
Buffer barriers are now manually inserted by DSMS instead of being handled by Veldrid, which allows for more optimal barriers. Vertex and index staging buffers are now directly mapped and read into by the resource loaders instead of copied into by another temp buffer, reducing memory usage and copy overhead when loading a map. This should allow for slightly faster map loading times.
> Add barrier commands and directly map vertex/index staging buffers

- StudioCore/MsbEditor/SceneTree.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioCore/TextEditor/FMGBank.cs
- StudioCore/TextEditor/TextEditorScreen.cs
- StudioCore/Utils.cs
Adds text wrap to map meta names, FMG entry preview, and param row names.
ImGui_WordWrapString() is pretty silly, but decently functional. I'm open to suggestions on how to improve it.
(Also includes a minor improvement in fmgbank.cs)
> Add text wrap to various UI elements

- StudioCore/AssetLocator.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
Changes DS2 param loading: loose params will only override regulation params when "loose params" project setting is true.
Makes loose param loading use _defs instead of independently loading them (Significantly improves load time in common circumstances)
> DS2: Fix non-loose param loading priority & fix loading defs multiple times

- FSParam/Param.cs
- StudioCore/MsbEditor/Entity.cs
- StudioCore/MsbEditor/MergedParamRow.cs
- StudioCore/MsbEditor/PropertyEditor.cs
- StudioCore/ParamEditor/MassParamEdit.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamReloader.cs
- StudioCore/ParamEditor/ParamUtils.cs
- StudioCore/ParamEditor/SearchEngine.cs
- StudioUtils/StridedByteArray.cs
Polishing work on FSParam to help make it more usable outside of DSMS:
* Add lots of documentation and usage advice to public methods
* Rename some fields to names that make more sense
* Add Param constructor that takes a paramdef
* ApplyParamdef will properly create the backing param data when the param is created from scratch
> FSParam usability

- SoulsFormats/SoulsFormats/Formats/MSB/MSB.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB1/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB1/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB3/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PointParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBB/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBB/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBD/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBD/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBN/MSBN.PartsSection.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBS/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBS/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBS/PointParam.cs
- StudioCore/MsbEditor/MsbEditorScreen.cs
- StudioCore/MsbEditor/SceneTree.cs
- StudioCore/MsbEditor/Universe.cs
When a missing reference is found, tell user referring entity's name and prompt to automatically select it in editor.
(Also fixes a crash in SceneTree)
> Improve handling of missing MsbEntry refs

- StudioCore/Editor/Action.cs
- StudioCore/Editor/AliasBank.cs
- StudioCore/Editor/TaskManager.cs
- StudioCore/MsbEditor/MtdBank.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioCore/ParamEditor/ParamReloader.cs
- StudioCore/Resource/ResourceManager.cs
- StudioCore/TaskLogs.cs
- StudioCore/TextEditor/FMGBank.cs
Lets TaskLogs store log priority, currently affecting whether they will appear in the main menu bar (and in the future, filterable in the full log window)
And because this required another variable passed through TaskManager funcs, it was restructured to use the new LiveTask class to keep things a bit more organized and easier to modify in the future.
(Also removes close window X from "Resource List", in ResourceManager.cs)
> Implement task log priority. Restructure TaskManager a bit.

- StudioCore/MsbEditor/Gizmos.cs
Makes gizmo with bounding box origin work properly when selection contains more than one entity
> Gizmo bbox origin w/ multiple selections

- StudioCore/MapStudioNew.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
New project dialog gave a warning regarding this, but import row names in the param menu did not.
> Add 2nd warning about DS2 non-loose param row names

- FSParam/Param.cs
> FSParam: don't ApplyParamDef when cloning a param

- SoulsFormats/SoulsFormats/Formats/MSB/MSB.cs
Case insensitive fallback fixes save errors because of certain vanilla collision references in ER, which have different letter casing for ModelParam name and collision ModelName.
Also rewords MissingReferenceException's message to not be inaccurate in some cases.
> Make MsbEntry FindIndex (by name) fallback to case insensitive

- StudioCore/MsbEditor/Entity.cs
Done because ds3 has a decent amount of 0 radius spheres. Iffy on whether this is the best solution.
> Entity: if scale is 0 0 0, clamp to min value

- FSParam/Param.cs
Fixes a crash after upgrading params. Same deal as #556
> Copy columns when cloning FSParam param

- StudioCore/ParamEditor/ParamEditorScreen.cs
Puts a warning in UI when all upgrade param checks pass except for version threshold
> (1.8.1) Tell user when param upgrade requires DSMS update

- StudioCore/Resource/ResourceManager.cs
Notably conveys the problematic resource's name to user, so they actually know what is at fault.
> Try/catch issues with LoadBinderResources and log them

- StudioCore/TextEditor/TextEditorScreen.cs
Needed to be removed because it was not (easily) compatible with line wrapped text.
> Remove ListClipper from fmg editor

- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
- SoulsFormats/SoulsFormats/Util/BinaryReaderEx.cs
Didn't want to add separate signed/unsigned methods because that would involve changing all of the existing calls
> Msb: add missing enum read value types

- StudioCore/AssetLocator.cs
- StudioCore/MapStudioNew.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
Strips DS2 row names from saved params on param save.
Saves DS2 row names to external files on param save.
Restores external row name files on project load.
Done in part because apparently loose params, like regulation, crash with too many row names. Text that stated this incorrect info was also removed.
> Strip and store DS2 row names to external files on save

- SoulsFormats/SoulsFormats/Formats/BTL.cs
(BTL v15 is used exactly twice in ER)
Created BTL LightSize field, and use it to determine number of fields instead of BTL version.
> Support BTL v15, implement LightSize

- StudioCore/MsbEditor/Action.cs
Now stores old and new object in constructor so that upon undo/redo, the same objects will be used instead of different ones. This fixes issues with other actions not being able to undo/redo since the wrapped objects would be different.
> ChangeMapObjectType improvements

- StudioCore/AssetLocator.cs
- StudioCore/MsbEditor/AssetBrowser.cs
- StudioCore/MsbEditor/ModelEditorScreen.cs
Builds model editor caches upon selecting model category instead of project load (improves DSMS startup time by a decent amount on slower hard drives).
> Model editor: build cache on category select, fix ER map models

- StudioCore/MapStudioNew.cs
Bad fix, but immediately necessary because startup tasks need to finish before DSMS can do certain things.
> Hotfix: startup tasks never finishing due to soapstone server task

- Directory.Build.props
Replaces the absolute path leading up to the project folder in exception track traces with ".", which not only prevents doxxing the respective build compiler's folder structure - which may potentially include their OS profile name - but also makes the exceptions more readable.
> Avoid doxxing developer paths when throwing exceptions

- StudioCore/Editor/Action.cs
- StudioCore/Editor/AliasBank.cs
- StudioCore/Editor/TaskManager.cs
- StudioCore/MapStudioNew.cs
- StudioCore/MsbEditor/MtdBank.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/ParamEditor/ParamEditorScreen.cs
- StudioCore/ParamEditor/ParamReloader.cs
- StudioCore/TextEditor/FMGBank.cs
Attempts to simplify usage and improve clarity for TaskManager. Will likely do more regarding this in the future since I don't like some parts of it.
Adds passive LiveTask vs active LiveTask distinction to handle tasks that are expected to run as long as DSMS is running, or potentially other long running background tasks. Only applied to soapstone server task at the moment.
> TaskManager refactor, passive LiveTasks

- StudioCore/AssetLocator.cs
Happened in cases where new maps were introduced.
> Fix BTL asset locator error when map folder doesn't exist in game data

- StudioCore/ParamEditor/ParamBank.cs
Makes duplicate defs no longer necessary, and uses ParamTypes from previous games.
The one wrench thrown into all of this is the fact EquipParamWeapon_NPC.param's def is EQUIP_PARAM_WEAPON_ST and is not compatible with EquipParamWeapon.param, which has a missing ParamType.
For now, I made EquipParamWeapon.param use ParamType EquipParamWeapon_TENTATIVE via EquipParamWeapon_PC.xml.
This kinda sucks and I can easily be convinced of alternative ideas.
> Use TentativeParamType dict for missing AC6 ParamTypes

- SoulsFormats/SoulsFormats/Formats/FLVER/FLVER2/FLVER2.cs
Add 0x10 as a valid assert for a value in FLVER2s, Comment note on AC6 flver version
> Add 0x10 as a valid assert for a value in FLVER2s, Comment note on AC6 flver version

- StudioCore/ParamEditor/AutoFill.cs
Looks like there was a typo and one always had the wrong id, but the issue didn't appear because they were inside different parent IDs. That changed, and the param menu got mixed with the row menu.
> Fix autofill menu duplication

- SoulsFormats/SoulsFormats/Util/SoulsFile.cs
- StudioCore/ParamEditor/ParamBank.cs
- StudioCore/Utils.cs
- Don't check for compression on AC6 param read because some params can pass DCX.Is check after just being resaved.
- Store (and restore write) invalid AC6 paramTypes for params that were given tentative paramtypes on read (better compatibility with other tools and format changes).
- Check AC6 paramdefs to catch future potential garbled paramtypes.
- Log params that are unable to find a corresponding paramdef for all games.
> AC6 param improvements + better paramdef x paramtype logging

- SoulsFormats/SoulsFormats/Formats/DCX.cs
- SoulsFormats/SoulsFormats/Util/Oodle.cs
Extremely likely this doesn't matter, but just in case it does this ensures that games will can use the oodle they came with.
> Allow preferred oodle to use based on compression

- StudioCore/ParamEditor/ParamBank.cs
This also has the benefit of ignoring fake zlib compression on all param reads.
> Fix not being able to read default DS3 params

- SoulsFormats/SoulsFormats/Formats/PARAM/PARAMDEF/XmlSerializer.cs
- StudioCore/Assets/Paramdex/DS2S/Defs/AREA_PARAM.xml
- StudioCore/Assets/Paramdex/DS3/Defs/ATK_PARAM_ST.xml
- StudioCore/Assets/Paramdex/DS3/Defs/ATTACK_ELEMENT_CORRECT_PARAM_ST.xml
- StudioCore/Assets/Paramdex/DS3/Defs/NETWORK_PARAM_ST.xml
- StudioCore/Assets/Paramdex/DS3/Meta/ATK_PARAM_ST.xml
- StudioCore/Assets/Paramdex/DS3/Meta/ATTACK_ELEMENT_CORRECT_PARAM_ST.xml
- StudioCore/Assets/Paramdex/DS3/Meta/NETWORK_PARAM_ST.xml
- StudioCore/Assets/Paramdex/ER/Defs/CoolTimeParam.xml
- StudioCore/Assets/Paramdex/ER/Defs/DefaultKeyAssign.xml
- StudioCore/Assets/Paramdex/ER/Defs/NetworkParam.xml
- StudioCore/Assets/Paramdex/ER/Meta/CoolTimeParam.xml
- StudioCore/Assets/Paramdex/ER/Meta/DefaultKeyAssign.xml
- StudioCore/Assets/Paramdex/ER/Meta/GameSystemCommonParam.xml
- StudioCore/Assets/Paramdex/ER/Meta/NetworkParam.xml
- StudioCore/Assets/Paramdex/SDT/Defs/CoolTimeParam.xml
- StudioCore/Assets/Paramdex/SDT/Defs/NetworkParam.xml
Renames fields when the same field appears multiple times.
This should help not only with user tools such as mapstudio's editor and massedit, but should help support versioned paramdef fields better.
> De-duplicate paramdef names

- SoulsFormats/SoulsFormats/Formats/MSB/MSB1/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB2/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB3/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PointParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBB/EventParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBB/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
- SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
This is done by assigning property instantiator.
The alternative is to insert an assignment for each enum into each constructor, as we have done so far for some reason.
Hopefully we can tell this problem to go away entirely when we finally come up with msbdefs.
> Always instantiate MSB enums with an enum value.

- StudioCore/Assets/Paramdex/AC6/Defs/TentativeParamType.csv
- StudioCore/ParamEditor/ParamBank.cs
Adds tentative paramtype for spEffectParam, which was stripped from AC6 1.02.1 regulation.
Makes parambank load loop continue when tentative paramtype cannot be found (in order to continue to log errors instead of being able to throw an exception)
> Tentative paramtype fixes

- DSMapStudio/Program.cs
- DSMapStudio_LowRequirements/Program.cs
- StudioCore/MapStudioNew.cs
- StudioCore/ParamEditor/ParamBank.cs
Remove AggregateException fluff from error messages if there is only 1 inner exception.
Improve crash handler message formatting for readability.
If params cannot be found, check game type and state relevant information so the user can resolve it.
Use tasklogs instead of messageboxes for some errors.
> Error handling and message improvements

- StudioCore/ParamEditor/ParamMeta.cs
- StudioCore/ParamEditor/ParamRowEditor.cs
- StudioCore/ParamEditor/ParamUtils.cs
Make CalcCorrectDefinition work with FCS param calculation curves (present in #685).
Fixes bug with plot if final growval was lower than first growval.
Fix plot not fitting well on screen.
Other visual improvements.
> Set up CalcCorrectDefinition for FCS param + improvements

- StudioCore/Editor/TaskManager.cs
Fixes stack trace not being helpful.
> Log inner exception information for silent fail tasks.

- StudioCore/MsbEditor/PropertyEditor.cs
- StudioCore/ParamEditor/ParamRowEditor.cs
- StudioCore/Utils.cs
More helpful version of #704. Retains improvements made there (shows more decimals), but also restores trailing zeroes for integer floats so users can still easily identify float values vs non floats.
> Imgui float input display format: retain trailing zeroes

- StudioCore/AssetLocator.cs
- StudioCore/MsbEditor/Universe.cs
- StudioCore/Resource/FlverResource.cs
Material fix seems to be the same story as #599.
DS2 chr textures still aren't working, in spite of texture info being delivered to resource handler. Not sure why.
> Ds2 material rendering fix + DS2 chr texture path setup

- SoulsFormats/SoulsFormats/Formats/DCX.cs
This is for parity with sf which apparently never got fixed.
> Fix zlib being included in dcx check

- SoulsFormats/SoulsFormats/Formats/MSB/MSB.cs
Prevents MSBs being unreadable if index reference is invalid (which can be caused by an msb having 0 ref entries)
> Check if MSB FindName index is >= list length

- SoulsFormats/SoulsFormats/Binder/BXF4/BXF4.cs
- StudioCore/MsbEditor/Universe.cs
- StudioCore/Utils.cs
Fixes DS2 BTLs not saving due to MemoryMappedFile BXF4 not being disposed.
Makes BTL saving use Utils.WriteWithBackup().
Makes Utils.WriteWithBackup() handle BXF3 and BXF4 properly.
> Fix DS2 BTLs saving by fixing BXF4 write/disposal. Improve BTL saving.

- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSB.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSB1/EventParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/EventParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PointParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBB/EventParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBD/EventParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBE/EventParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBS/EventParam.cs
- src/Studio.Core/SoulsFormats/SoulsFormats/Formats/MSB/MSBS/PointParam.cs
Makes MSB MissingReferenceExceptions (and helpers) work with MSB.FindIndicies() instead of just MSB.FindIndex()
> Support MSB MissingReferenceException for MSB.FindIndicies()

- src/StudioCore/MsbEditor/ObjectContainer.cs
Prevents missing model reference issues that occurs in unmodified maps.
> MSBE: Ignore case when determining model part type

- src/StudioCore/KeyBindings.cs
- src/StudioCore/MsbEditor/Action.cs
- src/StudioCore/MsbEditor/DisplayGroupsEditor.cs
- src/StudioCore/MsbEditor/Entity.cs
Adds option to select drawgroups from highlights.
Adds ability to change render groups for every entity in selection.
Adds vertical scrollbar to window.
Show names of targeted entities (accounting for CollisionName references & equivalents)
Some cleanup and optimization.
> Render group editor improvements

- src/StudioCore/MsbEditor/Universe.cs
Fix checking vanilla params instead of primary bank.
> DS2 map load: loaded params requirement fix

- src/StudioCore/ParamEditor/ParamBank.cs
- src/StudioCore/ParamEditor/ParamEditorScreen.cs
- src/StudioCore/Utils.cs
Newer version of #442 without the conflicts.
Also, this has been in a couple releases at this point. And because of it there have been SUBSTANTIALLY fewer people doing something wrong.
> Backup regulation before upgrading & clarify upgrade instructions (2)

- src/Studio.App/DSMapStudio_LowRequirements/DSMapStudio_LowRequirements.csproj
- src/Studio.App/DSMapStudio_LowRequirements/Program.cs
- src/StudioCore/MapStudioNew.cs
- src/StudioCore/MsbEditor/AssetBrowser.cs
- src/StudioCore/MsbEditor/SceneTree.cs
(The static bool is a bit silly, yes)
Also fixes low requirement exe octokit trimming issues (which was separately already fixed in 1.09.X releases)
> Low requirements mode: disable map/model editors, fix update checker

- src/StudioCore/ParamEditor/ParamBank.cs
People keep thinking green message = bad and this clogs up the logs anyway so 🤷
> Make successful tentative ParamType logs debug-level

- src/StudioCore/MsbEditor/SearchProperties.cs
- src/StudioCore/Utils.cs
Fixes range selection including entities not included in property search filter.
> Use filtered entity list when selecting range in property search

- src/StudioCore/TextEditor/FMGBank.cs
- src/StudioCore/TextEditor/TextEditorScreen.cs
Sorts filtered FMG entries by ID.
Auto-fills entry filter when using search all FMGs.
Fixes search all FMGs being able to show dupes in FMG list.
Fixes search all FMGs not displaying certain grouped/patch entry results properly.
> FMG editor fixes/improvements

- src/StudioCore/CFG.cs
- src/StudioCore/SettingsMenu.cs
- src/StudioCore/WorldView.cs
Stuttering was being caused by SDL.WarpMouseInWindow(), which starting having issues after we updated SDL2. SDL.WarpMouseGlobal() doesn't have that issue so we can just use it instead.
> Fix viewport camera stutter & add setting for camera sensitivity

- src/StudioCore/KeyBindings.cs
- src/StudioCore/TextEditor/FMGBank.cs
- src/StudioCore/TextEditor/FmgExporter.cs
- src/StudioCore/TextEditor/TextEditorScreen.cs
Adds new FMG import/export functions that with custom formatting that greatly simplifies modifying the text externally.
Benefits of the new format:
- Extremely readable plain text format. Metadata for each entry is located in a single header line.
- Combines duplicate entries, so identical FMG entries (such as with weapon infusions) can be modified from a single exported entry.
Old Json import/export format is considered obsolete, import function has been left in for now but exporting is disabled.
Also adds options to export modified text only and merge imported text, allowing for things like trivial text mod merging and exporting mod text for translations.
> Better FMG exporter

- src/StudioCore/CFG.cs
- src/StudioCore/MapStudioNew.cs
- src/StudioCore/SettingsMenu.cs
It's been reported that this reduces physical pain while using the program, which I think is pretty high priority.
It's worth investigating alternative defaults too, but I'm not sure what should be done in that regard (59.997/59.94? Not using floats?)
> Add settings for viewport FPS

- src/Andre/Andre.Native/ImGui.cs
Most relevant to multiline, prevents stackoverflow on super-large allocs.
The threshhold is set way below that just on a matter of principle, and only functionally affects csv import windows etc.
Does ugly up those lines of code a little, unfortunately.
> Don't use stackalloc for large buf sizes

- src/Andre/Andre.Native/ImGui.cs
- src/StudioCore/MsbEditor/SceneTree.cs
Hopefully this isn't a massive memory leak. The failure-case on utf8 encoding persists.
> Fix imgui input text - length + ctrlv crash

- src/StudioCore/CFG.cs
- src/StudioCore/MapStudioNew.cs
- src/StudioCore/SettingsMenu.cs
* Monitor DPI is correctly fetched from the system
* Monitor DPI scaling gets added to UI scale
* Monitor DPI scaling can be toggled off in the settings
* Fixed a long-standing issue where non-default UI scale would cause list scrolling to behave incorrectly
> feat: proper DPI handling
