soulsmods/DSMapStudio

StudioCore/Assets/Aliases/ER/MapNames.txt

Add Vawser's map IDs list to map aliases

Add a set of map name aliases for use in the map editor

---

StudioCore/MapStudioNew.cs

Minor fixes from bugs reintroduced in the merge.
C# text utilities, including CSV behaviour, should resume functioning as they did before the merge.
Param view preferences should now load.

Fix Text Culture, Fix loading prefs

---

StudioCore/MapStudioNew.cs

May leave branch open if other shortcut issues are discovered

Fix save shortcut, add save-all shortcut

---

StudioCore/MsbEditor/Universe.cs

fix ds3 map save

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/EventParam.cs
StudioCore/Editor/EditorDecorations.cs
StudioCore/MsbEditor/PropertyEditor.cs
StudioCore/ParamEditor/ParamRowEditor.cs

…using existing ref annotations
also fixes msbe itemlot ref

Adds paramref decorations to msb propertyEditor.

---

StudioCore/ParamEditor/MassParamEdit.cs

Fix CSV output

---

StudioCore/MapStudioNew.cs
StudioCore/MsbEditor/SceneTree.cs

Prepare for release:
* Set version string
* Add some resources including wiki links and discord server links
* Fix some useless UI elements appearing in model editor

version 1.0 prep

---

StudioCore/CFG.cs
StudioCore/Gui/Viewport.cs
StudioCore/MsbEditor/ModelEditorScreen.cs
StudioCore/Scene/SceneRenderPipeline.cs
StudioCore/WorldView.cs

Also increases default max clip distance from 20k to 50k.
UI to configure these (and other settings) in-program coming later.

Set & Get viewport FOV, Camera Speed, Max Clip Distance from local config

---

SoulsFormats/SoulsFormats/Formats/MSB/MSB.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSBE/EventParam.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSBE/MSBE.cs

Needed for PatrolInfo references to work

Fix event disambiguation

---

StudioCore/ParamEditor/ParamRowEditor.cs

Also adds warning in case of similar error

Fix dummy8 being added to propcache

---

StudioCore/ParamEditor/ParamRowEditor.cs

Makes diff still show up on refs

Separate param diff colouration and text colouration

---

DSMapStudio/DSMapStudio.csproj
DSMapStudio/imgui.ini.backup
StudioCore/MapStudioNew.cs

Include imgui.ini.backup file, make sure .ini's exist when trying to copy

Fix imgui.ini.backup stuff

---

StudioCore/MsbEditor/Universe.cs

Was already checking on load, now also checks on save.

Check for region duplicate Entity IDs on save

---

StudioCore/Editor/UIHints.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Not 100% perfect, but more accurate and useful than existing text.
More updates may come, but PR'ing as a matter of any-help-better-than-no-help

Update and improve massedit/search help text, add extras to help menu

---

StudioCore/MsbEditor/SceneTree.cs

Makes things consistent and fixes a minor issue

MSB map object list multi-select improvements 2

---

StudioCore/MapStudioNew.cs

Fixes missing JP characters and loads characters for more languages.

Load more glyphs from fonts

---

StudioCore/Editor/ProjectSettings.cs
StudioCore/MapStudioNew.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Also removes threading hack in new names

Contain all new project config, fix new project default names

---

StudioCore/MsbEditor/MsbEditorScreen.cs

No longer tries to get target map by selection. Also indirectly prevents create menu crash.

Add map selection menu to MSB Create menu

---

StudioCore/ParamEditor/ParamBank.cs

With the massive performance improvements this can be re-enabled

Auto refresh dirtycache on param load

---

StudioCore/ParamEditor/ParamRowEditor.cs

Updates propcache for these, as propcache was used previously and would crash if it was still null

Fix enums and ref context menu edits

---

FSParam/Param.cs
StudioCore/MapStudioNew.cs
StudioCore/ParamEditor/ParamBank.cs

* Make sure caches are cleared when switching projects
* Add code to try and fixup borked 1.06 params

1.02.1 fixes

---

StudioCore/MsbEditor/AssetBrowser.cs
StudioCore/MsbEditor/ModelEditorScreen.cs
StudioCore/MsbEditor/MsbEditorScreen.cs

* Move some racy tasks when switching projects back to the main thread
* Clear map list cache in the asset browser.

Fix race conditions

---

StudioCore/AssetLocator.cs
StudioCore/MapStudioNew.cs

Should allow DSMS to be functional without UXM now

Catch DirectoryNotFoundException for certain AssetLocator functions

---

StudioCore/MsbEditor/MtdBank.cs
StudioCore/TextEditor/FMGBank.cs
StudioCore/TextEditor/TextEditorScreen.cs

This allows the tasks to fail gracefully and not block loading new projects

Catch file IO errors with FMG and MTD loading

---

StudioCore/ParamEditor/MassParamEdit.cs

-Fixes single csv output for new params
-Fixes  single csv output header
-Fix expected single csv import header
-Corrects change count on some massedits
-Removes Ian

Fix single csv output and header, fix import header, remove drunk coding

---

StudioCore/Assets/Paramdex/ER/Names/ItemLotParam_enemy.txt
StudioCore/Assets/Paramdex/ER/Names/ItemLotParam_map.txt
StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Configurable single csv import to ignore missing rows

---

StudioCore/ParamEditor/MassParamEdit.cs

Real rewrite of operations pending

Avoid excess trimming, fix replace command

---

StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamUtils.cs

Rewrote vanilla ds2 param loading to make sure it's loading generators ig

Row difference lenience for duplicate paramdefs. 

---

StudioCore/ParamEditor/MassParamEdit.cs

cut my life into pieces
this is my final fix
total replacement, no patching
don't give a damn if it waits til 1.03

Fix stage not being advanced for separate param and row stages

---

StudioCore/MsbEditor/SearchProperties.cs

Fixes MSB prop search not initially refreshing when you right-click context search a property

Minor MSB prop search fix

---

DSMapStudio/Program.cs

Should stop folks launching through start menu and not finding oodle or assets etc

Set working directory from exe location

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBB/PartsParam.cs

Adjustments based on feedback from foxyhooligans

MSBB Improvements

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs

Split an int16 into 2 bools (distinct values were 0, 1, 256, 257).
Label some Unks.
Rename NPCArea to FastTravelRestriction.

MSBE unks & names

---

StudioCore/MsbEditor/Entity.cs

Also prevents a very specific crash

Fix check for valid CollisionName reacting to empty strings

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Serves as a fast Copy/Paste with slightly modified behavior. Notably increments row ID of copied row until an unused ID has been reached instead of lowest possible row ID (something I will probably change in a different PR)

Add Duplicate Param Rows function

---

StudioCore/MsbEditor/Entity.cs
StudioCore/Utils.cs

Fixes ImGui not displaying certain map object names (some vanilla objects have offending names)

Remove ## in Entity PrettyName

---

StudioCore/MsbEditor/MsbEditorScreen.cs
StudioCore/MsbEditor/Universe.cs

Fixes loading bars not appearing, among other async tasks that would occur doing map load.
Retains the fix that #172 accomplishes, but no longer causes issues.

Fix issues stemming from map load async changes

---

DSMapStudio/imgui.ini
DSMapStudio/imgui.ini.backup
StudioCore/CFG.cs
StudioCore/InputTracker.cs
StudioCore/KeyBindings.cs
StudioCore/MapStudioNew.cs
StudioCore/MsbEditor/AssetBrowser.cs
StudioCore/MsbEditor/DisplayGroupsEditor.cs
StudioCore/MsbEditor/ModelEditorScreen.cs
StudioCore/MsbEditor/MsbEditorScreen.cs
StudioCore/MsbEditor/SearchProperties.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamRowEditor.cs
StudioCore/TextEditor/TextEditorScreen.cs
StudioCore/WorldView.cs

Introduces rebindable keys for hotkeys and controls.
Keys can be bound in-program by the user, and binds are saved in a file within the DSMapStudio config folder.
New binds are implemented through the Bindings class, and are referenced similarly to CFG values.

Keybind System

---

StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Basic system to auto apply massedits upon upgrade

---

StudioCore/AssetLocator.cs
StudioCore/MsbEditor/SceneTree.cs

Loads BTL files in project folder, but not game folder (IE user-created BTLs).
Adds UI element to hide all lights within individual BTL.

BTL improvements

---

DSMapStudio/Program.cs
StudioCore/MapStudioNew.cs

Crash handler now properly logs all wrapped exceptions, displaying additional information needed for debugging.

Improve crash handler functionality

---

StudioCore/MsbEditor/Action.cs
StudioCore/MsbEditor/PropertyEditor.cs

Fixes enum edits not triggering Commit, and fixes model field changes updating model before Commit.

MSB propeditor fixes

---

StudioCore/Assets/Paramdex/ER/DefsPatch/10701000/FinalDamageRateParam.xml

Make internal name formatting consistent and fix def version in case we ever start caring about that.

Cleanup FinalDamageRate paramdef & make def version accurate.

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Fixes issue introduced in #210, issue was never present in any release.

Fix oversight in param upgrade whitelist

---

StudioCore/CFG.cs
StudioCore/MapStudioNew.cs

Open In Explorer menu with project/game/config options

---

StudioCore/Editor/ProjectSettings.cs
StudioCore/MapStudioNew.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/Utils.cs

Adds UI buttons in new project menu that describes what's what.
Renames "Load Default Row Names" to "Import Row Names".
"Import Row Names" box is now ON by default.

Add hints to New Project menu & additional clarification

---

StudioCore/Assets/Paramdex/ER/Names/NpcParam.txt

Update NpcParam.txt
Update names. Data is obtained following these priorities:
* FMG via NPCParam.nameID
* FMG via  DisplayBossHealthBar in emevd via entityID
* CharaInitParam.txt via entity charainit
* TalkESD via three digit NPC ID from emevdparam
* DarkScript3 model name list

Npcparams names update

---

StudioCore/Assets/Paramdex/DS2S/Names/BulletParam.txt

Reverts loss of information resulting from #173

Revert paramdex names for DS2 BulletParam

---

StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/TextEditor/TextEditorScreen.cs

Keeps selected row/entry on screen while row/entry searchbox is being modified.

Scroll to selected Param Row/FMG Entry while using searchbox

---

StudioCore/AssetLocator.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Adjusted text of "Upgrade Params" option and loosened detection of regulation.bin file name.
Allows for selection like this:

Small tweaks to Upgrade Params and regulation.bin detection

---

StudioCore/MsbEditor/Action.cs
StudioCore/MsbEditor/DisplayGroupsEditor.cs
StudioCore/MsbEditor/Entity.cs
StudioCore/MsbEditor/MsbEditorScreen.cs

Makes edits work properly to undo/redo.

Make render group editor use Actions

---

StudioCore/MsbEditor/AssetBrowser.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamRowEditor.cs

Fixes a couple things from #254, and improves visuals for param field editor UI.

UI fixes and minor improvements

---

StudioCore/KeyBindings.cs
StudioCore/MsbEditor/DisplayGroupsEditor.cs
StudioCore/MsbEditor/MsbEditorScreen.cs

Fixes Hide All keybind not being functional.
Swap Dummify/Un-Dummify default keybindings, place Dummify option before Un-Dummify in menu bar UI and keybind UI

Minor keybind adjustments/fix

---

StudioCore/Assets/Paramdex/ER/Meta/MenuPropertyLayoutParam.xml
StudioCore/Assets/Paramdex/ER/Meta/MenuValueTableSpecParam.xml
StudioCore/Editor/EditorDecorations.cs
StudioCore/MsbEditor/PropertyEditor.cs
StudioCore/ParamEditor/ParamMeta.cs
StudioCore/ParamEditor/ParamRowEditor.cs
StudioCore/TextEditor/FMGBank.cs

May have further updates for efficiency

Add FMG refs from param

---

SoulsFormats/SoulsFormats/Formats/MSB/MSB2/PartsParam.cs
StudioCore/Assets/Paramdex/DS2S/Meta/HIT_GROUP_PARAM.xml

HitFilterID and additional HitGroupID info

Minor MSB2 defs

---

StudioCore/Assets/Paramdex/ER/Meta/CalcCorrectGraph.xml
StudioCore/ParamEditor/ParamMeta.cs
StudioCore/ParamEditor/ParamRowEditor.cs

Limited by an inability of basic imgui plotlines to control x coordinates.

Add graphs for calccorrectgraphs

---

StudioCore/Gui/Viewport.cs

Ctrl+Click in viewport toggles selection (same as scenetree)

Viewport selection improvements

---

StudioCore/CFG.cs
StudioCore/MapStudioNew.cs
StudioCore/Scene/GPUBufferAllocator.cs
StudioCore/Scene/Renderable.cs
StudioCore/Scene/Renderer.cs
StudioCore/Utils.cs

Adds settings for Flver bone buffer and renderables.
Makes relevant exceptions mention these new settings.
Also minor settings UI tweaks.

Add settings for limits

---

StudioCore/ParamEditor/ParamMeta.cs

Will be doing this as thread collection issues crop up

Make FieldMetas concurrent

---

StudioCore/ParamEditor/MassParamEdit.cs

Includes random floating, random integer, and random from a field with a given row selector

Add random argumentGetters for massedits

---

StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/SearchEngine.cs

UI is touched up a little but still not idea.
However, it also serves as automatic documentation on the search and edit tools.

Command insert popups

---

StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamUtils.cs
StudioCore/ParamEditor/SearchEngine.cs

Reduces repeated code
Includes massedit stat getters

Param Edit cleanups

---

StudioCore/InputTracker.cs
StudioCore/WorldView.cs

Fixes issue caused by #332. Issue was never in a release.

Fix viewport camera speed modifier keys not working

---

StudioCore/ParamEditor/MassParamEdit.cs

Access value of cell before toParamEditorString

---

StudioCore/Assets/Aliases/DS3/MapNames.txt
StudioCore/Assets/Aliases/ER/MapNames.txt

Fix ds3 map alias, add ER map alias

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs

Connection MapID2.
Asset AssetUnkStruct3 Unk14.

MSBE mapID field improvements

---

StudioCore/Assets/Paramdex/ER/Names/ItemLotParam_enemy.txt
StudioCore/Assets/Paramdex/ER/Names/ItemLotParam_map.txt
StudioCore/Assets/Paramdex/ER/Names/TalkParam.txt

Fix duplicate row names in ER paramdex

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs

UnkStruct2 DispGroups: int[] -> uint[]
ConnectCollision MapID: byte[] -> sbyte[]

Minor MSBE part improvements

---

DSMapStudio.sln
StudioCore/MapStudioNew.cs
StudioCore/SettingsMenu.cs

Also adds "EnableEldenRingAutoMapOffset" setting to the settings menu, which was previously absent.

Separate settings menu from mapstudionew.cs

---

StudioCore/Editor/EditorDecorations.cs
StudioCore/Editor/UIHints.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamRowEditor.cs

Makes Mass Edit context menu when right clicking a field value collapsible.
Puts param field wiki "?" on the left side of rows.
Misc formatting so things look good.
Also adds Compact Mode setting, but that is disabled for now since it'll require merging with #402

Tweak param field UI

---

StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

* Import for all params vs. only current param
* Override all names, or only import over empty names

Expand "Import Row Names" with more options

---

StudioCore/Assets/Paramdex/ER/Names/WwiseValueToStrParam_BgmBossChrIdConv.txt

BgmBossChrIdConv param row names

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs

EnvironmentMapBox UnkT24, UnkT28, UnkT2E
EnvironmentMapPoint MapID2

MSBE EnvironmentMapBox and EnvironmentMapPoint fields

---

StudioCore/MsbEditor/MsbEditorScreen.cs
StudioCore/MsbEditor/Universe.cs

Now stores stack trace properly.

Improve map load exception handler

---

StudioCore/CFG.cs

I take full responsibility for its initial implementation. Always knew it was stupid but did not properly think about it.

Fix cfg load loop

---

StudioCore/CFG.cs
StudioCore/Editor/EditorDecorations.cs
StudioCore/MapStudioNew.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamRowEditor.cs
StudioCore/SettingsMenu.cs

Renames some config options to better match their current uses.
Makes Param_ShowSecondaryNames on by default.
Adds the rest of the compact param setting (which I forget to do in the original PR, oops)
Adds UI tab to settings menu
Decapitalizes settings (everything is now consistent)

Settings tweaks

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PartsParam.cs
StudioCore/MsbEditor/Action.cs

Rename Unk08 to InstanceID
Make map obj clone action generate a unique InstanceID

ER Unk08 + map object clone action interaction

---

StudioCore/ParamEditor/MassParamEdit.cs

This is also fixed in masseditvars (by replacing the whole shit thing)

Fix massedit op failure setting value to default instead of erroring

---

StudioCore/ParamEditor/ParamMeta.cs

Fix crashes on saving in editormode

---

StudioCore/Assets/Paramdex/DS3/Meta/CACL_CORRECT_GRAPH_ST.xml
StudioCore/Assets/Paramdex/ER/Meta/CalcCorrectGraph.xml
StudioCore/ParamEditor/ParamMeta.cs
StudioCore/ParamEditor/ParamRowEditor.cs
StudioCore/ParamEditor/ParamUtils.cs

Formatting is awkward for 5+ digit numbers, but this is an imgui limitation and won't be solved with more polish. Implot when?

Add soulcostdef graphing to calccorrectgraph

---

StudioCore/Assets/Paramdex/ER/Meta/EquipParamGoods.xml
StudioCore/ParamEditor/ParamMeta.cs
StudioCore/ParamEditor/ParamRowEditor.cs

Add capability for External File References in param editor

---

StudioCore/Assets/Paramdex/ER/Defs/WorldMapPointParam.xml
StudioCore/Assets/Paramdex/ER/DefsPatch/10310059/BonfireWarpParam.xml
StudioCore/Assets/Paramdex/ER/DefsPatch/10310059/WorldMapPointParam.xml
StudioCore/Assets/Paramdex/ER/DefsPatch/10501000/SoundCutsceneParam.xml

No NT yet, need loading support for it first

Backport paramdefs for earlier ER versions

---

StudioCore/KeyBindings.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Add param "goto selected row" option

---

StudioCore/MsbEditor/Universe.cs
StudioCore/Utils.cs

Former fixes modifying composite region properties.
Latter gives composite regions a "point region" model marker.

Class array prop edit fix & placeholder composite region model marker (crash fix)

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBS/EventParam.cs

MBSS WREntry unks

---

StudioCore/Assets/Paramdex/DS3/Meta/FACE_PARAM_ST.xml

DS3 FACE_PARAM meta

---

StudioCore/MsbEditor/MsbEditorScreen.cs
StudioCore/SettingsMenu.cs

Also makes offset distance setting UI element drag float

Make Move Selection To Camera maintain relative positions for multiple selections

---

StudioCore/KeyBindings.cs
StudioCore/MsbEditor/MsbEditorScreen.cs
StudioCore/SettingsMenu.cs

Adds option to rotate multiple selected objects around the central pivot.
Renames arbitrary rotation Y/X to Yaw/Roll

Add arbitrary rotation pivot & other tweaks

---

StudioCore/Graphics/VulkanGraphicsContext.cs
StudioCore/Scene/Renderer.cs
StudioCore/StudioCore.csproj
Veldrid.Utilities/DisposeCollectorResourceFactory.cs
Veldrid/BackendInfoVulkan.cs
Veldrid/CommandBufferPool.cs
Veldrid/CommandList.cs
Veldrid/GraphicsDevice.cs
Veldrid/ObjectPool.cs
Veldrid/RenderPassDescription.cs
Veldrid/ResourceFactory.cs
Veldrid/Swapchain.cs
Veldrid/VkFramebuffer.cs

Behind the scenes stuff. Mostly make queue types more explicit and make more objects pooled and tying lifetimes of temporary GPU resources to frames. Still needs work, but DSMapstudio still works so.

More renderer fun

---

SoulsFormats/SoulsFormats/Formats/MSB/MSBE/PointParam.cs
StudioCore/Assets/Paramdex/ER/Defs/AssetGeometryParam.xml
StudioCore/Assets/Paramdex/ER/DefsPatch/10701000/GameSystemCommonParam.xml
StudioCore/Assets/Paramdex/ER/Meta/SpEffect.xml

Includes sorting out some dummy/reserve fields that became used after patches

More ER Defs

---

StudioCore/Graphics/VulkanGraphicsContext.cs
StudioCore/Graphics/VulkanImGuiRenderer.cs
StudioCore/Scene/FullScreenQuad.cs
StudioCore/Scene/GPUBufferAllocator.cs
StudioCore/Scene/Renderer.cs
StudioCore/Scene/SceneRenderPipeline.cs
Veldrid/Buffer.cs
Veldrid/BufferDescription.cs
Veldrid/BufferPool.cs
Veldrid/CommandList.cs
Veldrid/CommonStrings.cs
Veldrid/GraphicsDevice.cs
Veldrid/Pipeline.cs
Veldrid/ResourceFactory.cs
Veldrid/ResourceSet.cs
Veldrid/Swapchain.cs
Veldrid/Texture.cs
Veldrid/TextureView.cs
Veldrid/Veldrid.csproj

Continue the migration to tracking resources per frame and eliminating reference counting.

More renderer work

---

StudioCore/Assets/Paramdex/DS1/Meta/ShopLineupParam.xml
StudioCore/Assets/Paramdex/DS1R/Meta/ShopLineupParam.xml
StudioCore/ParamEditor/MassEditScript.cs

Meta included just to get it out of the way

Masseditscript fix 2 + random ds1 meta

---

StudioCore/ParamEditor/SearchEngine.cs

Remove accidental comments

---

StudioCore/ParamEditor/AutoFill.cs
StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/SearchEngine.cs

Adds UI elements explaining what filters do, what operations do, and what operation argumentgetters do

Massedit Wiki texts

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Some issues were introduced because they are within an imgui table now

Fix compact UI for param rows

---

StudioCore/MsbEditor/MsbEditorScreen.cs

Fixes crashes for backup renderer

Disable display menu when there is no display

---

StudioCore/TextEditor/TextEditorScreen.cs

Improves performance, and actually removes lag for mega-huge FMGs

Use imgui list clipper for FMG entries

---

StudioCore/Platform/PlatformUtils.cs

Done to be consistent with winforms MessageBox.

Reverse MessageBox button order

---

SoulsFormats/SoulsFormats/Binder/BND3/BND3.cs
SoulsFormats/SoulsFormats/Binder/BND4/BND4.cs
SoulsFormats/SoulsFormats/Binder/BXF3/BXF3.cs
SoulsFormats/SoulsFormats/Binder/BXF4/BXF4.cs
SoulsFormats/SoulsFormats/Binder/IBinder.cs
SoulsFormats/SoulsFormats/Util/MountedSoulsFile.cs
StudioCore/MsbEditor/MtdBank.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/TextEditor/FMGBank.cs
Veldrid/GraphicsDevice.cs

Change uses of the binders to reflect this fact

Make binders disposable since they maintain mapped memory

---

StudioCore/Assets/Paramdex/ER/Meta/AtkParam.xml
StudioCore/Assets/Paramdex/ER/Meta/SpEffect.xml
StudioCore/Editor/EditorDecorations.cs

Updates some small meta, makes vref menu handle multiple fields within 1 param.
VRefs mechanism may be expanded to handle lookups more efficiently in the future.

Meta updates + multiple vref menu options

---

StudioCore/MapStudioNew.cs

Prevents crash-on-startup loops in more circumstances.
If there's an exception before all initial-load tasks added to TaskManager are able to complete, modify CFG during crash recovery to remove LastProjectFile

Clear "recent project" in CFG on initial load exceptions

---

SoulsFormats/SoulsFormats/Formats/MSB/Shape.cs
StudioCore/MsbEditor/Entity.cs
StudioCore/MsbEditor/PropertyEditor.cs
StudioCore/MsbEditor/Universe.cs

Support MSB shape rect

---

StudioCore/Editor/Action.cs
StudioCore/Editor/AliasBank.cs
StudioCore/Editor/TaskManager.cs
StudioCore/MapStudioNew.cs
StudioCore/MsbEditor/MtdBank.cs
StudioCore/MsbEditor/Universe.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamReloader.cs
StudioCore/TaskLogger.cs
StudioCore/TaskLogs.cs
StudioCore/TextEditor/FMGBank.cs

Second attempt that uses Microsoft.Extensions.Logging as a base.
Feels weird.
> Used to record and notify info useful to the user, such as loading and saving.
> 
> Adds log to main menu bar along with button to show full log history. Handles multiple colors for different log entry types and does some silly color transition stuff for better visual feedback.
> 
> (Also makes "Tasks" menu bar item always visible, just disabled when there are no running tasks)

Task logger (2)

---

SoulsFormats/SoulsFormats/Formats/MSB/MSB3/PartsParam.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSBB/PartsParam.cs

Courtesy of foxyhooligans, who used some debug function to generate this info. 
> "Game -> HIT INS -> WORLD HIT MAN -> mXX_00_00_00 -> scroll to the bottom there is MapStudioExp"

BB/DS3 SceneGparamConfig fields

---

StudioCore/MsbEditor/Entity.cs
StudioCore/MsbEditor/PropertyEditor.cs
StudioCore/MsbEditor/Universe.cs

Used at least once (!!) in bloodborne.

Support MSB shape circle

---

StudioCore/Assets/MassEditScripts/ER/GenerateAffinity.txt
StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/StudioCore.csproj

Adds utils to open script folder, reload scripts on demand
Removes the Store operation and adds paramlookup which is more appropriate

Masseditscript Cleanup

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Uses correct if pattern for tables

Fix crash when paramview goes offscreen

---

StudioCore/Assets/MassEditScripts/DS2S/Remove Names.txt

Obv useful for decreasing filesize of regulation.

Add remove names script for ds2

---

StudioCore/Editor/EditorDecorations.cs
StudioCore/MsbEditor/PropertyEditor.cs
StudioCore/ParamEditor/ParamRowEditor.cs

Blame ivi for throwing more actionmanager around I hate the lack of central repo for these contextual items

Inherit or proliferate name tool

---

StudioCore/Editor/TaskManager.cs
StudioCore/MapStudioNew.cs
StudioCore/MsbEditor/Action.cs
StudioCore/MsbEditor/Entity.cs
StudioCore/MsbEditor/MsbEditorScreen.cs
StudioCore/MsbEditor/PropertyEditor.cs
StudioCore/MsbEditor/Universe.cs
StudioCore/ParamEditor/MassEditScript.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamMeta.cs
StudioCore/ParamEditor/ParamRowEditor.cs
StudioCore/TaskLogs.cs
StudioCore/TextEditor/FMGBank.cs

Replaces TaskManager WarningList with TaskLogs functionality.
"Warnings" menu in menu bar is maintained by new warning list system in TaskLogs. Logs with types of warning/error and priority of normal/high will be placed into warning list as well as logger.
Logs with high priority display a MessageBox.
Identical logs in the logger added in sequence will be consolidated and have a "x2"+ added at the end of the message, with the count increasing as more are added.

TaskLogs 3

---

StudioCore/TextEditor/FMGBank.cs

Also makes SummarySwordArts a description

Group tutorial fmgs

---

StudioCore/ParamEditor/ParamBank.cs

Fixes crash when changing projects

Fix meta not being marked as unloaded quickly enough

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Puts a warning in UI when all upgrade param checks pass except for version threshold

Tell user when param upgrade requires DSMS update

---

StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs

Reworked CSV export menu.
Added options to export all rows / modified rows

Param CSV export menu improvements

---

StudioCore/MapStudioNew.cs

Also resolves some mystery issue with the await in CheckProgramUpdate never finishing.

Initialize soapstone server and program update check through TaskManager

---

StudioCore/Editor/Action.cs
StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamIO.cs

Includes naming differences, 1 or 2 menu name edits, and potentially a speedup.

Separate csv tools from massedit tools

---

StudioCore/Resource/FlverResource.cs

Fixes major texture rendering issues in DSR maps.
Not completely confident this is correct, but it looks right.

Dsr material fix

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Prevents some crashes. This was a regression.

Fix param meta not being checked

---

StudioCore/ParamEditor/ParamEditorScreen.cs

Was slightly wrong from AC6 merge

Fix param upgrade menu display condition

---

SoulsFormats/SoulsFormats/Util/Oodle.cs

Fix oo2core_6 path check

---

StudioCore/ParamEditor/ParamBank.cs
StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/SearchEngine.cs

Seems to work fine. Bit concerned for touching default search but should be fine if it tests fine for a whole 10 minutes before release.

Add fmg to default search

---

StudioCore/AssetLocator.cs
StudioCore/MsbEditor/AssetBrowser.cs
StudioCore/MsbEditor/ModelEditorScreen.cs
StudioCore/MsbEditor/ModelEditorTypes.cs
StudioCore/Resource/FlverResource.cs

Add Part Model Viewing

---

SoulsFormats/SoulsFormats/Binder/BXF4/BXF4.cs
StudioCore/MsbEditor/Universe.cs

Fixes ds2 maps not being loadable.
Works, but not 100% confident it's correct. Probably look over.

Fix BXF4 memory mapped file issues

---

SoulsFormats/SoulsFormats/Binder/BXF4/BXF4.cs

Affects nothing atm, but fatcat

Fix BSX4 MountedSoulsFile type

---

StudioCore/Editor/UIHints.cs
StudioCore/ParamEditor/MassParamEdit.cs
StudioCore/ParamEditor/SearchEngine.cs

Also moves paramlookup to advanced massedit.

Extend massedit hints and rewrite help menu.

---

StudioCore/ParamEditor/ParamRowEditor.cs
StudioCore/Utils.cs

Fix param row property context menu crashing with % char

---

StudioCore/Assets/Paramdex/SDT/Meta/ActionGuideParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/ActionUnlockParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/AiSoundParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/AtkParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/BehaviorParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/BonfireWarpParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/BulletParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/EquipMtrlSetParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/EquipParamGoods.xml
StudioCore/Assets/Paramdex/SDT/Meta/EquipParamWeapon.xml
StudioCore/Assets/Paramdex/SDT/Meta/ItemLotParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/NpcParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/NpcThinkParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/ObjectParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/ResourceItemLotParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/ResourceItemParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/ShopLineupParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/SkillParam.xml
StudioCore/Assets/Paramdex/SDT/Meta/SpEffect.xml

Lots of Sekiro param meta

---

StudioCore/TaskLogs.cs

Logger popups display all relevant information now.
Also includes exception message as part of base message.

Improve info conveyed to user from logs with exceptions

---

StudioCore/Assets/Paramdex/ER/Meta/WorldMapPointParam.xml
StudioCore/Editor/EditorDecorations.cs
StudioCore/ParamEditor/ParamMeta.cs
StudioCore/ParamEditor/ParamRowEditor.cs

Also display each fmg element when ref'd
Also also adds controls to prolif/inherit name by fmg.
Also also also adds override control to prolif/inherit features to overwrite non-empty names.

Add multiple FMG refs, conditional FMG refs

---

StudioCore/Assets/GameOffsets/AC6/CoreOffsets.txt

Update paramBase offset

---

StudioCore/ParamEditor/ParamEditorScreen.cs
StudioCore/ParamEditor/ParamReloader.cs

Fixes hot reloading for AC6.
Properly handles and logs errors.
Informs user when a game does not support hot reloading.

Hot reload fix + better error handling

---

StudioCore/AssetLocator.cs
StudioCore/MsbEditor/ModelEditorScreen.cs
StudioCore/MsbEditor/MtdBank.cs
StudioCore/MsbEditor/Universe.cs

* DES objects and characters
* PTDE objects and some characters (some textures are not rendering despite making it into resource handler, not sure why)
* DSR objects and some characters (some textures require getting chrtpfbhd from chrbnd, then using it with chrtpfbdt in chr folder. I have no idea how to handle this with the current system)
* Some AC6 setup

Support textures for more cases

---

StudioCore/Editor/EditorDecorations.cs

Fixes a crash and wrong information displayed (and maybe other things too)

Fix param meta FmgRef

---

DSMapStudio/DSMapStudio.csproj

Fix update checker by not trimming Octokit

---

StudioCore/SettingsMenu.cs

Fixes never being able to open project settings menu

Ignore passive tasks for project settings menu

---

SoulsFormats/SoulsFormats/Formats/MSB/MSB2/EventParam.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSB2/PartsParam.cs
SoulsFormats/SoulsFormats/Formats/MSB/MSB2/PointParam.cs

Reverts soulsmods/DSMapStudio#715
Was accidentally pulled to master.

Revert "MSB2 defs (1.9.0)"

---

StudioCore/Assets/Paramdex/AC6/Meta/EquipParamBooster.xml

ac6 meta edit

---

SoulsFormats/SoulsFormats/Formats/PARAM/PARAMDEF/XmlSerializer.cs
StudioCore/Assets/Paramdex/DS2S/Defs/GENERATOR_PARAM.xml
StudioCore/Assets/Paramdex/DS3/Defs/ATK_PARAM_ST.xml
StudioCore/Assets/Paramdex/DS3/Defs/CEREMONY_PARAM_ST.xml
StudioCore/Assets/Paramdex/DS3/Defs/CULT_SETTING_PARAM_ST.xml
StudioCore/Assets/Paramdex/SDT/Defs/HitMaterialSpecialSettingParam.xml
StudioCore/ParamEditor/SearchEngine.cs

Validate fieldnames to a set of 'valid' characters

---

src/Andre/SoulsFormats/SoulsFormats/Formats/FLVER/FLVER0/FLVER0.cs

Function was unused.
PR'd on behalf of NatsuDragneelTheFireDragon.

Fix FLVER0 ComputeBoneWorldMatrix

---

StudioCore/MapStudioNew.cs
StudioCore/MsbEditor/Universe.cs

Try/catch BTL saving
Try/catch crash recovery saving

Better error handling (1.9.1) hotfix

---

StudioCore/Assets/GameOffsets/AC6/CoreOffsets.txt

Fix hot reloader for AC6 1.04  (1.9.1 hotfix 2)

---

src/StudioCore/MsbEditor/MsbEditorScreen.cs

Fixes selection rotation not being maintained.
Fixes issues when root translation has rotation.

Fix move selection to camera rotations

---

src/StudioCore/Editor/TaskManager.cs
src/StudioCore/TaskLogs.cs

Handle debug logs.
Include time in logs.
Slightly smarter TaskManager exception logging.

TaskLog / TaskManager improvements

---

src/StudioCore/CFG.cs
src/StudioCore/MapStudioNew.cs

Fixes some issues when there are multiple projects in the same location. Organizes and consolidates things.

Improve recent project handling

---

src/StudioCore/ParamEditor/ParamEditorCommon.cs
src/StudioCore/Utils.cs

Fix regression where param editor wasn't using float formatter (Either a merge issue or the Andre thing).
Fix infinity/NaN breaking float formatter.

Float formatting fixes

---

src/StudioCore/MsbEditor/SceneTree.cs
src/StudioCore/MsbEditor/SearchProperties.cs
src/StudioCore/Utils.cs

Consolidated selection handler for scenetree and prop search.
Proper support for keyboard selections in property search.
(I will move UI stuff out of utils one of these days)

Map editor selection keypress handler.

---

src/StudioCore/TaskLogs.cs

Give log timestamps leading zeroes

---

src/StudioCore/MsbEditor/MsbEditorScreen.cs
src/StudioCore/MsbEditor/PropertyEditor.cs
src/StudioCore/MsbEditor/SearchProperties.cs
src/StudioCore/MsbEditor/Universe.cs
src/StudioCore/Utils.cs

Makes prop search work with props within classes/structs and enums.

Make MSB prop search work with every prop type (2)

---

src/StudioCore/MsbEditor/ModelEditorScreen.cs

At a minimum fixes models lingering around in scene.

Fix model editor not disposing renderables

---

src/StudioCore/ParamEditor/ParamEditorScreen.cs
src/StudioCore/ParamEditor/ParamEditorView.cs

Technically a regression fix, though this behavior wasn't intentional until now.

Goto selected row on normal param change

---

src/StudioCore/AssetLocator.cs
src/StudioCore/FeatureFlags.cs
src/StudioCore/MsbEditor/MtdBank.cs
src/StudioCore/Resource/ResourceLoadPipeline.cs
src/StudioCore/Resource/ResourceManager.cs

Disables AC6 MSB feature flag since it's not ready.
Support AC6 asset textures, chr textures prep (something's up with character textures)
Adds some resource debug logging.

Disable AC6 MSB feature flag, debug logging, AC6 texture prep

---

src/Andre/SoulsFormats/SoulsFormats/Util/PropFinderUtil.cs

Skip index parameters in prop search

---

src/StudioCore/CFG.cs
src/StudioCore/DebugPrimitives/DbgPrimWireBox.cs
src/StudioCore/DebugPrimitives/DbgPrimWireGrid.cs
src/StudioCore/Gui/Viewport.cs
src/StudioCore/KeyBindings.cs
src/StudioCore/MsbEditor/MsbEditorScreen.cs
src/StudioCore/MsbEditor/ViewGrid.cs
src/StudioCore/Scene/RenderScene.cs
src/StudioCore/Scene/Renderable.cs
src/StudioCore/Scene/RenderableProxy.cs
src/StudioCore/SettingsMenu.cs
src/StudioCore/Utils.cs

Restructured the Settings Menu to place things in a more consistent place. 
Added tooltips for most of the options, same as the ? tooltip used in the params.
Added configurable coloring for the wireframe primitives

Settings Menu

---

src/StudioCore/AssetLocator.cs

Fix ER AEG textures

---

src/StudioCore/MapStudioNew.cs
src/StudioCore/MsbEditor/MsbEditorScreen.cs
src/StudioCore/ParamEditor/ParamEditorScreen.cs
src/StudioCore/ParamEditor/ParamRowEditor.cs
src/StudioCore/Tests/ParamUniqueInserter.cs

Moves function from tests menu to param editor menu. Also integrates the editor-mode-only function that had similar functionality

Make "search params for row ID" available to users

---

src/StudioCore/TextEditor/FMGBank.cs

Same story as params, the game can used compressed or decompressed files depending on the executable and we don't know which

Write DeS FMGs both compressed and decompressed

---

src/StudioCore/MsbEditor/DisplayGroupsEditor.cs
src/StudioCore/ParamEditor/ParamEditorScreen.cs
src/StudioCore/ParamEditor/ParamEditorSelectionState.cs
src/StudioCore/ParamEditor/ParamEditorView.cs

I fixed some bugs, the most important is in the `ParamEditorView`. "Select params..." inserts into the wrong text box.

small bug fixes

---

src/StudioCore/MapStudioNew.cs

Also removes redundant CFG saves

Prompt user instead of automatically removing project from recent projs

---

src/StudioCore/Editor/EditorDecorations.cs
src/StudioCore/ParamEditor/ParamRowEditor.cs

I really wanted it to scroll, but imgui can't anticipate/shrink the table, nor can I overlap the graph seamlessly. So this fixed solution is an ok compromise.

Use fixed view ratio to always show calccorrectgraph

---

src/StudioCore/TextEditor/FmgExporter.cs

Fixes FMG importer in merge mode and not including last entry in import file

FMG importer fixes

---

src/StudioCore/MapStudioNew.cs

Was this just not happening all this time? Nobody said anything.

Serialize project.json on save-all button

---

src/StudioCore/AssetBrowser/AssetBrowserScreen.cs

Instead of changing data ownership and threading model

Super hacky fix for assetbrowser

---

src/Andre/SoulsFormats/SoulsFormats/Formats/MSB/MSBS/PartsParam.cs

Fix Sekiro WalkRoutes not being read to string and being wiped for it
